# Backend CI Template
# 이 파일을 프로젝트의 .github/workflows/ci.yml에 복사하여 사용하세요.
#
# 필요한 설정:
# - Python 3.11+
# - PostgreSQL (서비스 컨테이너)
# - uv 패키지 매니저

name: Backend CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-${{ matrix.python-version }}-

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Ruff lint
        run: ruff check src/ tests/

      - name: Ruff format check
        run: ruff format --check src/ tests/

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-${{ env.PYTHON_VERSION }}-

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Mypy
        run: mypy src/

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-${{ matrix.python-version }}-

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run unit tests
        run: pytest tests/unit/ -v --tb=short

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_PRIMARY_DB_URL: postgresql://testuser:testpassword@localhost:5432/testdb
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: uv-${{ env.PYTHON_VERSION }}-

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U testuser && break
            sleep 1
          done

      - name: Run database migrations
        run: |
          # 마이그레이션 스크립트가 있는 경우 실행
          if [ -f scripts/migrate.sh ]; then
            chmod +x scripts/migrate.sh
            ./scripts/migrate.sh
          fi

      - name: Run integration tests
        run: pytest tests/integration/ -v --tb=short

  test-coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_PRIMARY_DB_URL: postgresql://testuser:testpassword@localhost:5432/testdb
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run tests with coverage
        run: |
          pytest tests/ \
            --cov=src \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            -v --tb=short

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7
